<?php

/**
 * ${Entityname}.php
 *
 * @copyright Copyright © ${commentsYear} ${CommentsCompanyName}. All rights reserved.
 * @author    ${commentsUserEmail}
 */
namespace ${Vendorname}\${Modulename}\Model\ResourceModel;

use Magento\Framework\DataObject;use Magento\Framework\Model\ResourceModel\Db\AbstractDb;

class ${Entityname} extends AbstractDb
{
    /**
     * Initialize resource model
     *
     * @return void
     */
    protected function _construct()
    {
        $this->_init('${vendorname}_${modulename}_${entityname}', 'entity_id');
    }

    protected function _prepareDataForTable(DataObject $object, $table)
    {
        //todo add here code to prepare data for submission to the database e.g. multiselect fields, empty string in number fields
        return parent::_prepareDataForTable($object, $table); // TODO: Change the autogenerated stub
    }
}
